### ISSUE TITLE
Allow IDurableClient to be injected thru DI

### ISSUE THREAD

**Issue by galvesribeiro** [Azure/azure-functions-durable-extension#1303]
Hello folks!

Now that Az Functions somehow properly support DI, I was trying to inject `IDurableClient` at the ctor on one of the types I have registered on DI so I can start a Durable Function from there. However, it looks like that type isn't being injected on the DI container...

Is there any workaround to allow that scenario?

It is really bad if we have to hand over on every method call an instance of the `IDurableClient` to the downstream types.

Thank you!

**Comment by cgillum** [comment]
`IDurableClient` is intended to be used as a binding parameter. Can you describe in more detail why it must be injected via ctor DI instead of as a binding parameter?

**Comment by galvesribeiro** [comment]
For example, I have a public GraphQL HTTP function which is the front face of my system. Whenever someone invokes it, it calls a series of types registered on my DI container. Inside one of those types, under some circumstances, on of those injected services needs to start a Durable function and I don't want to make an extra HTTP call, use a Queue or anything as it doesn't make much sense.  

I would like to be able to call from within those types injected from the DI into the main GraphQL function the Durable Function by using the `IDurableClient`.

The flow would be:

1. Some client invoke the GraphQL HTTP function;
2. When the function is created, some services are injected on its ctor that were registered at the Startup class using `builder.Services.AddSingleton<IMyService>()`;
3. The function invoke `IMyService.DoSomething()`;
4. `IMyService` injects on its ctor a `IDurableClient` and at the implementation of `DoSomething()`, it calls `IDurableClient.StartNewAsync(...)`
5. Function execution is completed.

I can do that by passing the `IDurableClient` to the method as a parameter with `IMyService.DoSomething(durableClient)` but that doesn't make sense at all...

Does it make sense @cgillum ?

**Comment by ConnorMcMahon** [comment]
Given the flow, I don't see why having the parameter `IMyService.DoSomething(IDurableClient durableClient)` is unreasonable. The way we populate `IDurableClient` is via input bindings. I don't think those play nicely with the Azure Functions DI pipeline, and while we could probably make something work, I don't see much gain as opposed to just making it a parameter to your method.

**Comment by galvesribeiro** [comment]
I think you are not following my point... The problem is not that the function receive it on the method parameter per se.

The problem is that `IMyService` is a service that has all its dependencies injected on it and the only way to inject things on it is thru the DI. Methods should not be polluted with that is an implementation detail and it hurt a lot testability.

I understand the binding mechanism is what is setting the function method argument Today, but I'm pretty sure there are ways to get the instance of the `IDurableClient` from the DI container rather then from the functions parameter and also provide a seamless way of having it work with the bindings to provide back compat support.

> I don't see much gain as opposed to just making it a parameter to your method

There is a huge gain (and a huge loss if not supported) in testability.  That is not a cosmetic issue _just_ because we can pass it as a method parameter. It is a real problem specially if you have one abstraction on top of that interface so you can make it testable or if this service type is not on the function project but instead it is on a shared nuget package.

**Comment by sebastianburckhardt** [comment]
The capability of creating a `IDurableClient` without having to use bindings makes sense to me, since clients are meaningful even outside of functions (in contrast to `IDurableOrchestrationContext `, `IDurableActivityContext`, or `IDurableEntityContext`). And DI seems like the most logical way to expose that capability. Would this be solved by the proposed changes in #1125 by any chance?

**Comment by galvesribeiro** [comment]
Hi @sebastianburckhardt nice to see you around!

So yeah! If the `IDurableClientFactory` has no dependencies on ASP.Net Core, is a regular `netstandard` package, and can be just injected by calling `IServiceCollection.AddDurableTask()` (and optionally allowing an `IOptions<DurableTaskConfig>` or something for config), that would do exactly what I wanted to. We would support not just services inside a function but also any external app like on console app or whatever to invoke orchestrations.

This has nothing todo with the orchestrator pieces as it should be treated as _just_ a client for the Durable Functions just like you mentioned. It is just a way to proper support DI and allow clients to be abstracted from the trigger infrastructure.

**Comment by cgillum** [comment]
I agree that this would be useful generally, and it looks like #1125 would make this possible.

**Comment by mmajcica** [comment]
I just checked and with the current latest this is still not fully possible. I was expecting that if I do specify IDurableClient as a dependency for my function class, the DI container will be able to solve it and give me the necessary instance. The only thing available in the container is IDurableClientFactory. It would be nice if the IDurableClient would be there so that we do not need to specify any extra code for registering and getting the IDurableClient.
