### ISSUE TITLE
Expired CreateTimer() events aren't processed at scheduled time

### ISSUE THREAD

**Issue by brttjwll** [Azure/azure-functions-durable-extension#1395]
### Description
When CreateTimer() is used to sleep function, there is a relatively significant delay between when the function is resumed and when the timer was scheduled to expire. Often this delay is 20-25 seconds, when using a 30 second timer this is significant. I would like to understand if this is correct use case and how I could improve this delay. 

Related to https://github.com/Azure/azure-functions-durable-extension/issues/684 and possibly https://github.com/Azure/azure-functions-durable-extension/issues/606

### Expected behavior
CreateTimer() for 30 seconds, expect function to be resumed when scheduled. 

### Actual behavior
CreateTimer() for 30 seconds, the function is resumed often 20-25 seconds after the timer was scheduled to expire.

### Relevant source code snippets

Here is my eternal orchestrator, following this example: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-eternal-orchestrations?tabs=csharp#periodic-work-example

```csharp
        [FunctionName("Periodic_Cleanup_Loop")]
        public static async Task Run(
            [OrchestrationTrigger] IDurableOrchestrationContext context,
            ILogger log)
        {
            await context.CallActivityAsync("DoCleanup", null);

            // sleep for 30 seconds
            DateTime nextCleanup = context.CurrentUtcDateTime.AddSeconds(30);
            await context.CreateTimer(nextCleanup, CancellationToken.None);

            if (!context.IsReplaying){ log.LogInformation($"Resumed at: {context.CurrentUtcDateTime}, nextCleanup was scheduled for: {nextCleanup}"); }

            context.ContinueAsNew(null);
        }

        [FunctionName("DoCleanup")]
        public static void DoCleanup([ActivityTrigger] IDurableActivityContext context, ILogger log)
        {
            log.LogInformation("DoCleanup running.");
        }
```

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.2.2
- **Azure Functions runtime version (1.0 or 2.0)**: 3
- **Programming language used**: C#

### If deployed to Azure

- **Timeframe issue observed**: 6/25/2020 6AM UTC - 6/25/2020 12PM UTC (And beyond)
- **Function App name**: PeriodicWorkExample20200624114312
- **Function name(s)**: Periodic_Cleanup_Loop, DoCleanup, Trigger_Eternal_Orchestration
- **Azure region**: East US
- **Orchestration instance ID(s)**: StaticID
- **Azure storage account name**: periodicworkexample20200

**Comment by cgillum** [comment]
Thanks for these details, they made it very easy for me to find your app and get some data.

It appears that you have multiple function apps sharing the same storage account and task hub.

![image](https://user-images.githubusercontent.com/2704139/85749955-23ddc780-b6be-11ea-808a-e339aaae260f.png)

Please ensure each Durable Functions app runs in its own task hub. Otherwise two function apps could conflict with each other, resulting in unpredictable behavior (including processing delays). For more information about task hubs and how they can be configured, please refer to the [Task Hub documentation](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-task-hubs).

Interestingly, the storage account shown here is different than the one you reported.

**Comment by ms-v-csacha** [comment]
@cgillum Here is an example that demonstrates this behavior locally as well, includes a screenshot of the run
[context.createTimerTriggerExample.zip](https://github.com/Azure/azure-functions-durable-extension/files/4832680/context.createTimerTriggerExample.zip)

**Comment by brttjwll** [comment]
I am a little confused by that as I published the function app from visual studio and created a new storage account.

I have tried again, this time I created the function in the portal, and deployed code using a release pipeline. Unless I am misunderstanding this process, I would expect this function to be using brettperiodicworkstorage (created new during the create process) and have it's own task hub called BrettPeriodicWorkTaskHub.

Example log message: 
6/25/2020, 9:07:54.442 PM | StaticId: Function 'Periodic_Cleanup_Loop (Orchestrator)' was resumed by a timer scheduled for '2020-06-25T21:07:26.9767195Z'. IsReplay: False. State: TimerExpired. HubName: BrettPeriodicWorkTaskHub. AppName: brett-periodic-work-app. SlotName: Production. ExtensionVersion: 2.2.2. SequenceNumber: 217.

### Updated app details...

**Timeframe issue observed**: 6/25/2020 8:49:59 UTC - 6/25/2020 9:08:23 UTC (and beyond)
**Function App name**: brett-periodic-work-app
**Function name(s)**: Periodic_Cleanup_Loop, DoCleanup, Trigger_Eternal_Orchestration
**Azure region**: East US
**Orchestration instance ID(s)**: StaticID
**Azure storage account name**: brettperiodicworkstorage

**Comment by brttjwll** [comment]
I can reproduce behavior running locally as well. 

I have tried reducing "maxPollingInterval" to the minimum in host.json, it had no effect, although I am not sure that configuration pertains to this scheduling issue.

Interestingly, reducing the length of the scheduled timer, appears to correlate with a reduced delay, when using a 10 second timer the function is resumed 4-6s after the timer was scheduled to expire. 

Ultimately, is the behavior I am observing really just the expected behavior? (That is 20-25s delay before being resumed after a 30s timer expires.)

I feel like this is simple to reproduce, so I am just curious if anybody else has this use case and is NOT seeing this. Are my efforts better spent working with the delay instead of trying to reduce it?

**Comment by ConnorMcMahon** [comment]
@brttjwll, sorry for the delay in responding.

I'm curious if this is an artifact of the [default value](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-bindings#durable-functions-2-0-host-json) for `maxQueuePollingInterval` being 30 seconds. If you are at that max queue polling interval due to app inactivity, then the 20-25 second delay could just be due to us only polling the queue every 30 seconds. 

I'm definitely not positive this is the case, but it may be worth temporarily decreasing that to a value like 5 seconds for a test app and seeing if that resolves the issue. Note that decreasing this value could increase storage transaction costs during periods of inactivity, so I wouldn't recommend this long term unless this issue is very important to you, but it would be a worthwhile test to run.

Unfortunately, the previous timestamp is now outside of our existing telemetry. Would you mind posting a new timestamp?

**Comment by jewelldev** [comment]
Hi thanks for the suggestion. I set maxQueuePollingInterval to 5 seconds in host.json file. I redeployed and restarted my test function app, but there was no observable difference. Still seeing greater than 20 second delays between when timer is scheduled to expire and the function is resumed. 

```
    "durableTask": {
      "hubName": "BrettPeriodicWorkTaskHub",
      "maxQueuePollingInterval": "00:00:05"
    }
```
**Timeframe issue observed**: 9/9/2020 2:00:00 AM UTC - 9/9/2020 1:00:00 PM UTC (and beyond)
**Function App name**: brett-periodic-work-app
**Function name(s)**: Periodic_Cleanup_Loop, DoCleanup, Trigger_Eternal_Orchestration
**Azure region**: East US
**Orchestration instance ID(s)**: StaticID
**Azure storage account name**: brettperiodicworkstorage

**Comment by brttjwll** [comment]
Hi thanks for the suggestion. I set maxQueuePollingInterval to 5 seconds in host.json file. I redeployed and restarted my test function app, but there was no observable difference. Still seeing greater than 20 second delays between when timer is scheduled to expire and the function is resumed.

```
    "durableTask": {
      "hubName": "BrettPeriodicWorkTaskHub",
      "maxQueuePollingInterval": "00:00:05"
    }
```
**Timeframe issue observed**: 9/9/2020 2:00:00 AM UTC - 9/9/2020 1:00:00 PM UTC (and beyond)
**Function App name**: brett-periodic-work-app
**Function name(s)**: Periodic_Cleanup_Loop, DoCleanup, Trigger_Eternal_Orchestration
**Azure region**: East US
**Orchestration instance ID(s)**: StaticID
**Azure storage account name**: brettperiodicworkstorage

**Comment by ConnorMcMahon** [comment]
@brttjwll,

Taking a look at the logs, it looks like this is still an issue with maxQueuePollingInterval.

The settings don't appear to have taken due to your host.json being slightly incorrect. In v2.x of the extension, we started using [nested configuration](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-bindings#durable-functions-2-0-host-json). Yours should look like this:

```
    "durableTask": {
      "hubName": "BrettPeriodicWorkTaskHub",
      "storageProvider": {
           "maxQueuePollingInterval": "00:00:05"
       }
    }
```

**Comment by ConnorMcMahon** [comment]
Out of curiosity, I took a look at our backoff strategy to track the delay as a function of how long it has been since the last message on this queue. You can find the code for our backoff strategy [here](https://github.com/Azure/durabletask/blob/master/src/DurableTask.AzureStorage/BackoffPollingHelper.cs#L47).

Poll attempt 0: delay = 00:00:00.0500000, cumulative time = 00:00:00.0500000
Poll attempt 1: delay = 00:00:00.1050000, cumulative time = 00:00:00.1550000
Poll attempt 2: delay = 00:00:00.1590000, cumulative time = 00:00:00.3140000
Poll attempt 3: delay = 00:00:00.2790000, cumulative time = 00:00:00.5930000
Poll attempt 4: delay = 00:00:00.4020000, cumulative time = 00:00:00.9950000
Poll attempt 5: delay = 00:00:00.7960000, cumulative time = 00:00:01.7910000
Poll attempt 6: delay = 00:00:01.8490000, cumulative time = 00:00:03.6400000
Poll attempt 7: delay = 00:00:03.0400000, cumulative time = 00:00:06.6800000
Poll attempt 8: delay = 00:00:05.1970000, cumulative time = 00:00:11.8770000
Poll attempt 9: delay = 00:00:11.9430000, cumulative time = 00:00:23.8200000
Poll attempt 10: delay = 00:00:23.3720000, cumulative time = 00:00:47.1920000
Poll attempt 11: delay = 00:00:30, cumulative time = 00:01:17.1920000
Poll attempt 12: delay = 00:00:30, cumulative time = 00:01:47.1920000
Poll attempt 13: delay = 00:00:30, cumulative time = 00:02:17.1920000
Poll attempt 14: delay = 00:00:30, cumulative time = 00:02:47.1920000
Poll attempt 15: delay = 00:00:30, cumulative time = 00:03:17.1920000
Poll attempt 16: delay = 00:00:30, cumulative time = 00:03:47.1920000
Poll attempt 17: delay = 00:00:30, cumulative time = 00:04:17.1920000
Poll attempt 18: delay = 00:00:30, cumulative time = 00:04:47.1920000
Poll attempt 19: delay = 00:00:30, cumulative time = 00:05:17.1920000

Note that a pattern emerges. The rule of thumb is that however long it has been since the queue has last successfully pulled a message is how long we will wait to poll the queue again, up to the maximum of the max queue polling interval (default of 30 seconds). 

That means that if you have very low traffic queues like in your application (with a single eternal orchestration) that sends a message every 30 seconds, you are always going to end up with a queue polling interval of ~24 seconds.

Essentially the only way to resolve this is to turn down your maximum queue polling interval to an acceptable value, or to increase traffic to your application so that you get more consistent messages to your queues. As soon as you get a single message on the queue, the polling interval will reset.

**Comment by cgillum** [comment]
@ConnorMcMahon that's good data. While this is a bit of a tangent, do you think it might make sense to slow down the rate at which we increase the polling delay? As I look at it, the backoff seems like it's ramping up pretty quickly...

**Comment by brttjwll** [comment]
Thanks, I corrected the error in my host.json. After retesting can confirm that reducing maxQueuePollingInterval has resolved the issue. Setting maxQueuePollingInterval to 5s reduced the delay to 1-3s.
