### ISSUE TITLE
Long waits before orchestration kicks off

### ISSUE THREAD

**Issue by qngEdg** [Azure/azure-functions-durable-extension#1904]
I'm on an EP1.
My host.json has the following
`"durableTask": {
      "hubName": "MyTaskHub",
      "storageProvider": {
        "connectionStringName": "AzureWebJobsStorage",
        "controlQueueBatchSize": 32,
        "controlQueueBufferThreshold": 256,
        "controlQueueVisibilityTimeout": "00:05:00",
        "maxQueuePollingInterval": "00:00:05",
        "partitionCount": 10,
        "trackingStoreConnectionStringName": "AzureWebJobsStorage",
        "trackingStoreNamePrefix": "DurableTask",
        "workItemQueueVisibilityTimeout": "00:05:00"
      }
    }`

I'm noticing really long waits before the executions are kicked off.

In App insights I have the following Logs:

- 7/30/2021, 7:46:15.068 Trigger fired
- 7/30/2021, 7:46:49.523 Orchestration started

Given I have  "partitionCount": 10 there should be plenty of scale out.
 "maxQueuePollingInterval": "00:00:05", should also catch the times when there are not many times.
Given EP1 should not have Cold starts either.

I've run a subsequent test and the wait times are more reasonable:
- 7/31/2021, 8:35:34.500 Trigger fired
- 7/31/2021, 8:35:34.810 Orchestration started.

It's certainly a little strange on the sporadic nature of when the events do occur.
We do have a number of timer events the run on every 5 mins and at the end of the day.
However I would have thought the 10 partitions would have been enough to cater for fan out scalability.

**Comment by amdeel** [comment]
Hey @qngEdg. This could be related to a bug we found in DurableTask.AzureStorage. We fixed in this bug in our DurableTask.AzureStorage 1.8.8 release. We just released a new Durable Functions extension package 2.5.1 today including this fix. Could you update to that package and let us know if you still have this problem?

**Comment by qngEdg** [comment]
Excellent. Will have a look and report back

**Comment by qngEdg** [comment]
Can I confirm the nuget package to install is: Microsoft.Azure.WebJobs.Extensions.DurableTask 2.5.1
![image](https://user-images.githubusercontent.com/70017909/128107574-1d1dfda0-c799-40f3-b1ae-eed4d8a0fd08.png)

**Comment by amdeel** [comment]
@qngEdg Yeah, 2.5.1 https://github.com/Azure/azure-functions-durable-extension/releases/tag/v2.5.1

**Comment by vany0114** [comment]
@amdeel what about the node js package? I've seen the same behavior too

**Comment by qngEdg** [comment]
We've been regression testing at present. Hopefully be able to get a close result after this has been completed.

**Comment by amdeel** [comment]
@vany0114 For JavaScript customers, you'll have to explicitly add this version of the NuGet package because we don't yet have an extension bundles release with this version. Use function cli to upgrade to Durable Functions 2.5.1. https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask

func extensions install <packagename> -v <version>

**Comment by qngEdg** [comment]
Please close

**Comment by ConnorMcMahon** [comment]
Glad to hear your issue has been fixed @qngEdg.

@vany0114, if you are a node customer experiencing this issue, it is likely a different root cause, as we don't have an extension bundle released that has the code containing this regression.  Can you file an issue (either this repo or the Durable JavaScript repo) with an instance id, UTC timestamp, and region, and we can take a look at your app?

**Comment by vany0114** [comment]
> @vany0114 For JavaScript customers, you'll have to explicitly add this version of the NuGet package because we don't yet have an extension bundles release with this version. Use function cli to upgrade to Durable Functions 2.5.1. https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask
> 
> func extensions install < packagename > -v < version >

Hi @amdeel, I added the Durable Functions 2.5.1 explicitly (as well as the Microsoft.Azure.WebJobs.Extensions.EventGrid because I have some EG triggers in that function app). So my question is: do I have to build the `extensions.csproj` manually locally as well as in the CI in order for it to work right? and when deploying I also have to carry over the `bin` and `obj` folders that are created after the build, right? 

BTW I've noticed very long delays (3 minutes or more) before the timer gets triggered, that's why I'm trying to do this workaround, would be nice to get the new extension bundles in a new version of the JS package.

**Comment by amdeel** [comment]
@vany0114 It looks like we did actually recently release a bundles version that references Durable Functions 2.5.1 so you shouldn't have to worry about explicitly referencing 2.5.1 anymore.
https://github.com/Azure/azure-functions-extension-bundles/releases/tag/2.8.3

But, like Connor mentioned, its not clear what issue you're facing so if after you upgrade you are still seeing problems you will have to open a separate issue with more details so we can look into the telemetry to investigate your app.

**Comment by vany0114** [comment]
@amdeel thanks, so I'll use the 2.8.3 bundles then:

can I do this to make sure it uses 2.8.3 as the min version?
```
"extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "(2.8.3, 3.0.0)"
  }
```

how can I confirm that it is using the Durable Functions 2.5.1 version after that change? just curious

**Comment by amdeel** [comment]
@vany0114 yeah, that looks correct.
2.8.3 will have Durable Functions 2.5.1.

**Comment by vany0114** [comment]
@amdeel and how can I confirm that the function app is using Durable Functions 2.5.1 once deployed? is there a way?
