### ISSUE TITLE
Some Orchestrations stuck awaiting an activity that has completed

### ISSUE THREAD

**Issue by olitomlinson** [Azure/azure-functions-durable-extension#774]
I have about 17 orchestrations (out of ~30k) all sat in the `running` state because they are awaiting on the completion of activities.

The activities have actually completed, because I can see the artefacts in my system that are generated when the activity runs.

Looking at the history, It appears like the activity never published the signal back to the orchestration or the orchestration never received the signal.

UK South
DF 1.8.0 (azure Functions V2) - Consumption
Excecution Id : 3fdfb591e9f64f169347411f2f1cb05e
Orchestration Id : fec5719d-3ae5-439b-bbfc-fba9d077fe72
timestamp : 2019-05-24T11:47:39.625Z

**Comment by olitomlinson** [comment]
@cgillum please can you shed some light on why this happened.

If our workflows unexpectedly breakdown like this it negatively affects our customers experience of our product :(

**Comment by cgillum** [comment]
Hey @olitomlinson, sorry for the delay, and sorry for the impact this is having on your customers!

I looked at your instance and it looks like the DTFx layer discarded an activity completion message (and also a raised event message) at `2019-05-24 11:55:49` because it thought that your orchestration had completed. I'm not sure _why_ it thought your orchestration had completed, though. I'll need to dig a bit deeper.

I did notice that you're running an older version of the extension (1.8.0 - we're now up to 1.8.2). The latest updates do include some reliability fixes, though it's not clear to me whether they would address your issue. It's something to consider, however, if it's not inconvenient.

**Comment by olitomlinson** [comment]
Thanks Chris 🙏🏻 

I was going to upgrade to 1.8.1 last week, but started seeing the performance issues so wanted to see if I could get to the bottom of that first before upgrading, but as I now can’t recreate the perf issues any more, there’s no reason to not upgrade! Many thanks once again, I really appreciate you taking the time to help me out!

**Comment by olitomlinson** [comment]
Not upgraded to 1.8.2 yet (A job for monday) but we had another incident today. 

Interestingly this one is different in that the `RuntimeStatus` is `Running` (and awaiting an activity response, according to my `customStatus`),

However, when observing the history table, all the signs indicate that the activity _did_ actually complete, the subsequent activity also completed, and the orchestration actually exited successfully and as expected. 

Orchestration Id : ffdfaab2-9e19-4df7-8b0b-e14695427f57
Exection Id: 8c27a9a647f64ba4a3b780fc3b29968d

**Comment by cgillum** [comment]
Instance `ffdfaab2-9e19-4df7-8b0b-e14695427f57` has the exact same signature as `fec5719d-3ae5-439b-bbfc-fba9d077fe72`.

What I'm noticing now which I didn't notice before is that the Durable Functions extension believes that the orchestration function actually completed. However, for some reason, the VM which completed the orchestration never actually deleted the completed queue messages, nor did it update the execution status in the **Instances** table. Following this, the messages became visible again on their control queues and were replayed on another VM, which then immediately discarded them claiming that the orchestration instance already completed.

This leads me to believe something happened to your VM between the time the orchestration completed and the execution status being updated, because otherwise another VM should not have picked up these messages. I'm going to dig a bit more to try and see what happened to this VM. Either way, I suspect we may have a consistency bug, because a VM failure should not leave you in an inconsistent state like this.

**Comment by cgillum** [comment]
So it looks like the Functions host shut down around the time this orchestration was trying to complete. It appears you are running on the Consumption plan, so this is not an unusual event if traffic is slowing down and instances are being scaled in.

Looking at the [DurableTask.AzureStorage code](https://github.com/Azure/durabletask/blob/1e3b2a0983c2365b57990d86cd4411a597bbee5f/src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs#L985-L1000), it appears that we try to update the **History** table prior to updating the **Instances** table. That means if there is a failure or a shutdown after writing to the **History** table but before updating the **Instances** table, then we can get stuck in this inconsistent state.  I'm guessing that this is what happened. A simple fix we can pursue is changing the order of the updates (Instances table first, then History table) so that we can eventually get back into a consistent state.

**Comment by olitomlinson** [comment]
@cg Upgraded my Dev environment today with 1.8.2 and ran a test. 

Unfortunately I've got the same results, approx 40 Orchestrations out of 18,000 are stuck in the `running` state awaiting a signal from the activity. The activity completed, but the signal was either never published or it never arrived.

Orchestration Id `551ae48a-5882-4102-95c8-a7e4dd162c52` Execution Id `fa4dbd79d44d49818b4ebe6328c85742`
Orchestration Id `bedfe305-7fc9-418b-897f-d17f97acd176`  Execution Id `e3cc9c3163c54c70ad184217257601cf`

**Comment by cgillum** [comment]
So @ConnorMcMahon looked at this more closely, and my original analysis was actually incorrect. This is actually a re-occurrence of a previously fixed issue (see https://github.com/Azure/azure-functions-durable-extension/issues/460) which recently regressed.

The new fix for this issue is here: https://github.com/Azure/durabletask/pull/299

**Comment by olitomlinson** [comment]
Great, thanks for the update! So glad I could help uncover a bug!

**Comment by olitomlinson** [comment]
@cgillum This is becoming painful for us in production to manage.

I have to regularly check the TaskHub Instances storage to find any 'Running' orchestrations, and then dig into my telemetry for every instance that looks suspicious, then restart the orchestration manually if it has become stuck. We are starting 10s of thousands of instances every day, so this is no easy task to keep on top of, which ultimately means the customer occasionally gets a poor experience of our product as we can't maintain our SLAs.

Please can you offer advice on a short-term mitigation if you are not able to offer an ETA on 1.8.3?

I'm becoming desperate so I'll even take a pre-release of DurableTask.AzureStorage and release my own fork of Durable Functions if that's what it takes.

Thank you for your support.

**Comment by cgillum** [comment]
Hi @olitomlinson - thanks for letting us know more about the impact to you - that sounds really painful :(. We have the fix merged but got delayed on release activities due to other urgent priorities on the team. I'll prioritize getting you a prerelease fix that you can validate - expect to hear back from me later today.

**Comment by olitomlinson** [comment]
@cgillum Thanks so much, Chris. It is really appreciated!

**Comment by cgillum** [comment]
We have a potential fix to the **Microsoft.Azure.DurableTask.AzureStorage** dependency available here: https://www.myget.org/feed/azure-appservice/package/nuget/Microsoft.Azure.DurableTask.AzureStorage/1.6.2-rc. Can you add a reference to this nuget package version and let us know if it resolves the issue?

**Comment by olitomlinson** [comment]
@cgillum a huge improvement but not entirely fixed.

I ran 4 tests (40k orchestrations in each test, so 160k in total)

3 tests worked flawlessly and then on the last test, just 1 orchestration got stuck.

Usually I would have seen between 5 - 50 stuck orchestrations when starting 40k orchestrations, so its definitely a huge improvement! 

Given that this will resolve 99% of my issues, Is it possible to get a pre-release version of 1.8.2 with the Azure Storage fix published to Nuget so I can at least get this into production?

Details for the orchestration that is stuck.

UK South
custom build of 1.8.2 (with AzureStorage 1.6.2-rc)
Orchestration Id : 1bde7c45-f8cb-4477-8709-e0ae2b1e9559
Exectuion Id : ad544c4eb3a7473da66e361bbbc99399

----

I will continue to do some more tests. 

Once again, thank you for all your support, it really makes a huge difference!

**Comment by olitomlinson** [comment]
Done a few more tests and I'm still getting failures :(

**Test 5** - 40k - 10 failed
Orchestration Id : 82c2b411-e404-41fd-8c8e-92ae2605b302
Execution Id : 9555df4a377a4f1b85f1248382581708

**Test 6** - 40k - 3 failed
Orchestration Id : abce25a4-8b8c-43a5-a24d-abc813816639
Execution Id : c8aae7ac430246d99502bb7aad2034b0

**Comment by cgillum** [comment]
Hmm...okay, we'll take a look at your latest runs to see if there's something we might have missed.

**Comment by ConnorMcMahon** [comment]
@olitomlinson 

Looking at our logs, all three of those instance ids you provided us still running on a version of the extension with **Microsoft.Azure.DurableTask.AzureStorage** v1.6.1. 

However, there are just over 160K instances successfully running on **Microsoft.Azure.DurableTask.AzureStorage** v1.6.2 in your account.

Is it possible the tests with stuck instances somehow got ran with the wrong version of the extension?

**Comment by olitomlinson** [comment]
@ConnorMcMahon 

I did republish my Function App again at 18:30 UTC and ran another 40k test and everything worked as expected, no stuck orchestrations.

I'm very suspicious that my Function App somehow rolled back, which produced the bad test results.

----

I will run some more tests and let you know the results.

**Comment by olitomlinson** [comment]
Ran another test and all 40k orchestrations completed successfully.

I'm going to leave the Function App alone now and test again in the morning (10 hours from now) and see what happens. If the app regresses back to orchestrations getting stuck then there is definitely something weird going on.

**Comment by cgillum** [comment]
Cool - since initial indication is that the fix works, I went ahead and published the official **Microsoft.Azure.DurableTask.AzureStorage** update to nuget.org: https://www.nuget.org/packages/Microsoft.Azure.DurableTask.AzureStorage/1.6.2

We'll make this dependency the default in the next **Microsoft.Azure.WebJobs.Extensions.DurableTask** release.

**Comment by olitomlinson** [comment]
@cgillum @ConnorMcMahon 

I've released and built my Function App using using 1.6.2 and I've had a couple of stuck orchestrations.

I can confidently say that neither me or my team have rolled-back the deployed code, so from my perspective there shouldn't have been a regression back to the previous version of AzureStorage.

If you look at the telemetry for the following instances, and find that it actually is referencing the old version of my Function App (which contains the old version of AzureStorage) then that must mean that the Functions Host is loading old .dlls of my Function App.

UK south
Orchestration Id : 6e94ef23-ae00-44d7-afe2-4fa8a4a91add
Execution Id : de48389fefba487eaed961dfd7ea79fe

Orchestration Id : 98acb78b-b8b7-4797-93d2-1ad5a0c3c0af
Execution Id : 4c100081ecc3478693eaa3a2cd677a0e

**Comment by ConnorMcMahon** [comment]
@olitomlinson 

I took a look at those orchestrations. It looks like they are indeed running the new code, and the behavior we are seeing is exactly what we would expect with the new code. We temporarily abandon the message 3 times before completely discarding the message, only to have the orchestration finally update the instance history shortly after. I'm not sure increasing the dequeue count to something like 10 or even 20 would be able to completely mitigate this scenario. 

Out of curiosity, what was the reduction in stuck orchestrations? Clearly our fix was not a total mitigation, but hopefully it reduces them by 80-90%.

@cgillum, we may need to take a deeper look into this scenario, and see if we can come up with a way to completely address this edge case.

**Comment by olitomlinson** [comment]
@ConnorMcMahon 

Not scientific but 40k orchestrations will typically generate between 5 and 50 stuck orchestrations.

Since testing with the update, I’ve not seen anything more than 5, so there’s definitely an improvement!

The difficulty for me is that I can’t easily automate the detection (and then restarting) of stuck orchestrations, as new orchestrations are entirely based on our customers actions, (not tasks that are initiated on a known schedule). I can’t simply make regular queries of the TashHubInstances and _know_ that any running instances are stuck, it requires me to drill into the history and then look for signs of it being stuck.

**Comment by ConnorMcMahon** [comment]
@olitomlinson I am attempting a more robust change that should hopefully remove the few remaining cases where we hit this race condition. If this approach doesn't work, I might need to completely change directions with how to fix this.

https://github.com/Azure/durabletask/pull/304.

**Comment by olitomlinson** [comment]
Thanks @ConnorMcMahon, I really appreciate you guys taking the time to find a solution for this!

If you need some more references, today we had 3 stuck orchestrations out of 7682.

Orchestration ID : 5371c676-b596-4fe1-a3bf-62fe18336d25
Execution ID : 8f7eceb3bf9c4306b5fdf775d402c84d

Orchestration ID : e6b2bf80-002a-4c62-9802-d3a680c36f6c
Execution ID : cb3401762acf4c238b31b27304768dc1

Orchestration ID : f70a08c3-7613-4607-8d77-7a4b9b3f2c88
Execution ID : d3f0777ae0754c7290f82c1f2b2cbced

**Comment by cgillum** [comment]
This fix has been released as part of v1.8.3. Let us know if you're still running into this with the latest bits.

**Comment by olitomlinson** [comment]
Initial testing looks good. Will continue monitoring! Thanks so much!

**Comment by chattersley** [comment]
I've tried this in 1.8.2 and 1.8.3 and still fails.

**Comment by cgillum** [comment]
@chattersley since this issue has already been closed, please open a new issue so we can properly track and investigate. Thanks!
