### ISSUE TITLE
Calling "rewind" on a failed function will not clear the output

### ISSUE THREAD

**Issue by Nican** [Azure/azure-functions-durable-extension#968]
### Description
I have a long-running durable function. The durable function failed due to a bad edge case, so I patched-up the code, redeployed, and called the "rewind" function. 

I was actually happily surprised that the function is now running from where it left off, but the "output" was not cleared. So the long-running durable function is still making progress, and updating the "customStatus", but the "output" is now not null.

As per the documentation (https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-http-api#get-instance-status), the output should be null when "the instance is not in a completed state."

### Expected behavior
I expect for the "output" to be null when the durable function is still running.

### Actual behavior
The "output" is not cleared from the error message when a failed function is `rewind`ed. 

### App Details
- **Durable Functions extension version (e.g. v1.8.3)**: v1.8.2
- **Azure Functions runtime version (1.0 or 2.0)**:  2.0
- **Programming language used**: C#

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**: Thu, 10 Oct 2019 18:25:20 GMT
- **Function App name**:
- **Function name(s)**:
- **Azure region**: West US2
- **Orchestration instance ID(s)**: ActiveDirectory
- **Azure storage account name**: 

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by kunjan13** [comment]
Any updates on this bug? is it fixed now??

**Comment by AdamCoulterOz** [comment]
The same thing happens if you start an instance with the same instance ID that has previously finished, starting a new orchestration (essentially using the orchestration instance id as a mutex lock), it will still have the output from the previous time it ran.

**Comment by davidmrdavid** [comment]
Hey all, thanks for reaching out and apologies for the late response here.

My understanding is that `rewind` is still a "preview" / experimental feature (as seen by the docs here: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-instance-management?tabs=csharp#rewind-instances-preview), which is probably why this hasn't been prioritized yet. That's probably why some of the edge cases, such as this one, are still a little rough. Still, I'll add this to our backlog to restart a discussion on the status of `rewind` and our plans moving forward, so thanks for the ping!

Finally, just a heads up that Connor is now with a different organization, so he _probably_ won't be responding to pings in these threads :) . Feel free to ping me, or any of the Durable Functions maintainers, instead!
